const
  Yellow* = "#FCFF82"
  Orange* = "#EF7575"
  Pink* = "#A8377B"
  Background* = "#FEFEFE"
  BackgroundDark* = "#181326"
  BackgroundSecondaryDark* = "#1c172a"
  ForegroundDark* = "#E0EFFE"
  BackgroundSecondary* = "#EFEFEF"
  Foreground* = "#212121"
  LinkForeground* = "#aca7fa"
  LinkActiveForeground* = "#ccccff"
  LinkVisitedForeground* = "#8c87aa"
